version: '3'

#VOLUMES
# volumes:
#   my-dir:
#     dirver

#NETWORK
networks:
 TestNetWork:
    external: true

#SERVICES
services:
  webspa:
    hostname: webspa
    container_name: webspa
    image: webspa:v1.0
    # volumes:
    #   - E:\Azure\WEB\6.Docker\WebAngular\WebTestAngular\default.conf:/etc/nginx/conf.d/default.conf
    build: .
    restart: always
    networks:
      - TestNetWork
    ports:
      - 4042:80
